#!/bin/sh

for env in dev prod; do for i in $(gcloud compute instances list --project=${env}-sh-t1-app-300917 | awk '/vmtodns/ {print $1}'); do gcloud compute instances delete $i --project=${env}-sh-t1-app-300917 --quiet; done; done
